 * Serving Flask app 'app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://10.176.12.215:5000
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 959-415-164
Traceback (most recent call last):
  File "/Users/mac/Documents/GitHub/N.A.I.D/backend/app.py", line 135, in <module>
    app.run(debug=True, host='0.0.0.0', port=5000)
  File "/Users/mac/Documents/GitHub/N.A.I.D/.venv/lib/python3.12/site-packages/flask/app.py", line 662, in run
    run_simple(t.cast(str, host), port, self, **options)
  File "/Users/mac/Documents/GitHub/N.A.I.D/.venv/lib/python3.12/site-packages/werkzeug/serving.py", line 1115, in run_simple
    run_with_reloader(
  File "/Users/mac/Documents/GitHub/N.A.I.D/.venv/lib/python3.12/site-packages/werkzeug/_reloader.py", line 459, in run_with_reloader
    ensure_echo_on()
  File "/Users/mac/Documents/GitHub/N.A.I.D/.venv/lib/python3.12/site-packages/werkzeug/_reloader.py", line 439, in ensure_echo_on
    termios.tcsetattr(sys.stdin, termios.TCSANOW, attributes)
termios.error: (4, 'Interrupted system call')
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/resource_tracker.py:254: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
